version: 2
jobs:
  deploy-website:
    working_directory: ~/vuls
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - website-node-modules-{{ checksum "website/yarn.lock" }}
            - website-node-modules-
      - run:
          name: Install node_modules
          command: |
            cd website
            yarn --no-progress
      - run:
          name: Install apt packages
          command: |
            sudo apt install rsync
      - save_cache:
          key: website-node-modules-{{ checksum "website/yarn.lock" }}
          paths:
            - website/node_modules
      - deploy:
          name: Publish gh-pages
          command: |
                  git config --global user.email "kotakanbe@users.noreply.github.com"
                  git config --global user.name "kotakanbe"
                  echo "machine github.com login kotakanbe password $GITHUB_TOKEN" > ~/.netrc
                  # install Docusaurus and generate file of English strings
                  cd website && npm install && npm run write-translations && cd ..
                  sudo apt-get install default-jre
                  wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
                  sudo dpkg -i crowdin.deb
                  crowdin --config crowdin.yaml upload sources --auto-update -b master
                  crowdin --config crowdin.yaml download -b master
                  cd website && npm install && GIT_USER=kotakanbe npm run publish-gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: master
